### PR TITLE
Document new "identity.fxaccounts.autoconfig.uri" desktop preference.

### PR DESCRIPTION
**Pull request by thomcc**
Let me know if this wasn't the right procedure for updating these docs.

(Also let me know if you think there's a better way to describe this situation, as it is I feel like the wording is a bit convoluted, but I'm not sure how better to explain it.)

### CODE REVIEW

**Comment by rfk** [comment]
SGTM, thanks @thomcc!  It may also be worth a quick note in `source/howtos/run-sync-1.5.rst` where it talks about `about:config`, to say "if you're also running your own Accounts sever, see here for a way to configure them all at once".

**Comment by thomcc** [comment]
How's this? (Not sure if it updated you when I updated the patch)

**Comment by rfk** [comment]
> (Not sure if it updated you when I updated the patch)

It didn't, thanks for the ping :-)

**Comment by rfk** [comment]
awesomesauce, thanks @thomcc!

**Pull request merged**
